### ISSUE TITLE
Add back host number to map marker

### ISSUE THREAD

**Issue by AmritasyaPutra** [stefansundin/traceroute-mapper#10]
I have been using your tool for few days and I noticed that you have updated it recently. The earlier map used to show the number, now it doesn't. This makes the map less helpful.

**Comment by stefansundin** [comment]
Thanks.

I wrote the OpenLayers code a few years ago but I didn't ship it back then. Now that I did, I didn't look that closely on what was missing.

Okay, so I managed to get a pretty simple number rendered like this (53e5b3ba3cd173f0a82c9bf3623b548bf2caa2e9):

![Screenshot 2024-09-17 at 22 26 22](https://github.com/user-attachments/assets/4991b872-c156-48ae-a81b-4168abc8abd5)

But I wanted to try to get an icon that looked like the old Google Maps pins, [and that was much harder](https://github.com/stefansundin/traceroute-mapper/commit/820f9564ad2c64a77eb0e6be42293c7c9ea94076) since OpenLayers doesn't seem to have a corresponding icon, but I got a custom one working:

![Screenshot 2024-09-17 at 22 29 13](https://github.com/user-attachments/assets/d4d51122-6444-4170-9b49-b8c99c8e26e4)

I also tried white text but I decided to leave it with black text, like before:

![Screenshot 2024-09-17 at 22 29 08](https://github.com/user-attachments/assets/9b5c6bc0-e03b-489b-9dc5-8f7f2b877b33)

And then finally, for reference, this is what it used to look like:

![Screenshot 2024-09-17 at 22 29 19](https://github.com/user-attachments/assets/85f4b4fb-e871-4965-b1ba-b84c3acd0ab5)

Anyway... hope that works for you. :)
